apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rud7pcju4-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rud7pcju4-java-springboot-gitops